# -*- coding: utf-8 -*-
"""StartingWithPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P17avTrn3oel7Xg1eJ0NkkPK08qaG8AW
"""



print("Hello World")

a="Hello"
print(a)

name=input("Enter your name:")
print(name)
age=int(input("What is your Age? "))
print(age)
print("Your name is "+name)

#WAP to dis name age & add
#WAP to swap numbers
#WAP convert float to integer